create table pu_busi_ind.bm_Accounts_recv_m10_1
(month_no      varchar2(6),
cust_type      varchar2(6),
order_no       number,
area_code      varchar2(6),
area_name      varchar2(16),
values_num1    number,
values_num2    number,
values_num3    number,
values_num4    number,
values_num5    number,
values_num6    number,
values_num7    number,
values_num8    number,
values_num9    number,
values_num10    number,
values_num11    number,
values_num12    number,
values_num13    number,
values_num14    number,
values_num15    number,
values_num16    number,
values_num17    number,
values_num18    number,
values_num19    number,
values_num20    number,
values_num21    number,
values_num22    number,
values_num23    number,
values_num24    number,
values_num25    number)

create table pu_busi_ind.bm_Accounts_recv_m10_2
(month_no      varchar2(6),
cust_type      varchar2(6),
order_no       number,
area_code      varchar2(6),
area_name      varchar2(16),
values_num1    number,
values_num2    number,
values_num3    number,
values_num4    number,
values_num5    number,
values_num6    number,
values_num7    number,
values_num8    number,
values_num9    number,
values_num10    number,
values_num11    number,
values_num12    number,
values_num13    number,
values_num14    number,
values_num15    number,
values_num16    number,
values_num17    number,
values_num18    number,
values_num19    number,
values_num20    number,
values_num21    number,
values_num22    number,
values_num23    number,
values_num24    number,
values_num25    number,
values_num26    number,
values_num27    number,
values_num28    number,
values_num29    number,
values_num30    number,
values_num31    number,
values_num32    number,
values_num33    number,
values_num34    number,
values_num35    number,
values_num36    number,
values_num37    number,
values_num38    number,
values_num39    number,
values_num40    number,
values_num41    number,
values_num42    number,
values_num43    number,
values_num44    number,
values_num45    number,
values_num46    number,
values_num47    number,
values_num48    number,
values_num49    number,
values_num50    number,
values_num51    number,
values_num52    number,
values_num53    number,
values_num54    number,
values_num55    number,
values_num56    number  )


update pu_busi_ind.bm_Accounts_recv_m10_1
set order_no=22
WHERE AREA_NAME='全省';
commit;
----sql
select nvl(t.order_no,a.order_no),
nvl(t.area_name,a.area_name),
nvl(values_num1 ,0),
nvl(values_num2 ,0),
nvl(values_num3 ,0),
nvl(values_num4 ,0),
nvl(values_num5 ,0),
nvl(values_num6 ,0),
nvl(values_num7 ,0),
nvl(values_num8 ,0),
nvl(values_num9 ,0),
nvl(values_num10,0),
nvl(values_num11,0),
nvl(values_num12,0),
nvl(values_num13,0),
nvl(values_num14,0),
nvl(values_num15,0),
nvl(values_num16,0),
nvl(values_num17,0),
nvl(values_num18,0),
nvl(values_num19,0),
nvl(values_num20,0),
nvl(values_num21,0),
nvl(values_num22,0),
nvl(values_num23,0),
nvl(values_num24,0),
nvl(values_num25,0) 
from  PU_META.LATN_NEW_ORDER a
left join pu_busi_ind.bm_Accounts_recv_m10_1 t 
on a.local_code=t.area_code  
and month_no ='201702'
and t.cust_type='合并' 
where a.local_code not in ('9001','9002') 
order by nvl(t.order_no,a.order_no); 

select 
select nvl(t.order_no,a.order_no),
nvl(t.area_name,a.area_name),
nvl(values_num1 ,0),
nvl(values_num2 ,0),
nvl(values_num3 ,0),
nvl(values_num4 ,0),
nvl(values_num5 ,0),
nvl(values_num6 ,0),
nvl(values_num7 ,0),
nvl(values_num8 ,0),
nvl(values_num9 ,0),
nvl(values_num10,0),
nvl(values_num11,0),
nvl(values_num12,0),
nvl(values_num13,0),
nvl(values_num14,0),
nvl(values_num15,0),
nvl(values_num16,0),
nvl(values_num17,0),
nvl(values_num18,0),
nvl(values_num19,0),
nvl(values_num20,0),
nvl(values_num21,0),
nvl(values_num22,0),
nvl(values_num23,0),
nvl(values_num24,0),
nvl(values_num25,0),
nvl(values_num26,0),
nvl(values_num27,0),
nvl(values_num28,0),
nvl(values_num29,0),
nvl(values_num30,0),
nvl(values_num31,0),
nvl(values_num32,0),
nvl(values_num33,0),
nvl(values_num34,0),
nvl(values_num35,0),
nvl(values_num36,0),
nvl(values_num37,0),
nvl(values_num38,0),
nvl(values_num39,0),
nvl(values_num40,0),
nvl(values_num41,0),
nvl(values_num42,0),
nvl(values_num43,0),
nvl(values_num44,0),
nvl(values_num45,0),
nvl(values_num46,0),
nvl(values_num47,0),
nvl(values_num48,0),
nvl(values_num49,0),
nvl(values_num50,0),
nvl(values_num51,0),
nvl(values_num52,0),
nvl(values_num53,0),
nvl(values_num54,0),
nvl(values_num55,0),
nvl(values_num56,0) 
from  PU_META.LATN_NEW_ORDER a
left join pu_busi_ind.bm_Accounts_recv_m10_2 t 
on a.local_code=t.area_code  
and month_no ='201703'
and t.cust_type='合并' 
where a.local_code not in ('9001','9002') 
order by nvl(t.order_no,a.order_no); 
