Select A.SERV_ID, A.USER_NAME, A.ACCT_ID, A.ACC_NBR
	From PU_WT.F_1_SERV_D_JF A
	Left Join PU_INTF.I_IN_KG_SERV_GRID Partition(P201710) F
		On A.SERV_ID = F.PROD_ID
	Left Join (Select * From PU_META.D_HX_ZD_ORG_BRANCH_TREE Where BRANCH_CODE3 = '85301970000') C
		On F.SUM_BRANCH_CODE = C.BRANCH_CODE
	Left Join PU_WT.WT_SERV_SHZ_ALL_201710 E
		On A.SERV_ID = E.SERV_ID
 Where E.SERV_ID Is Null
	 And C.BRANCH_CODE Is Not Null
